ALTER TABLE "Empresa" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Perfil" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Assinatura" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Negociacao" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "HistoricoPagamento" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "SistemaToken" DISABLE ROW LEVEL SECURITY;
